Affiliate_Shopee/Areas/Admin/Controllers/DealsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Affiliate_Shopee.Models;
using X.PagedList;
using Microsoft.AspNetCore.Authorization;

namespace Affiliate_Shopee.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin, SupportAdmin")]
    public class DealsController : Controller
    {
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly ShopeeAffContext _context;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public DealsController(ShopeeAffContext context, IHttpContextAccessor httpContextAccessor, IWebHostEnvironment hostingEnvironment)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
            _hostingEnvironment = hostingEnvironment;
        }

        public async Task<IActionResult> Index(int? page, string textsearch, string status, DateTime? createdat)
        {
            var pageNumber = page ?? 1;
            var pageSize = 10;
            var query = _context.Deals.Include(d => d.User).AsQueryable();
            if (!string.IsNullOrEmpty(textsearch))
            {
                query = query.Where(d => d.Name.Contains(textsearch) || d.Code.Contains(textsearch));
            }
            if (!string.IsNullOrEmpty(status))
            {
                query = query.Where(d => d.Status == status);
            }
            if (createdat.HasValue)
            {
                query = query.Where(d => d.CreatedAt.Value.Date == createdat.Value.Date);
            }
            query = query.OrderByDescending(d => d.CreatedAt);
            var deals = await query.ToPagedListAsync(pageNumber, pageSize);
            ViewBag.TextSearch = textsearch;
            ViewBag.Status = status;
            ViewBag.CreatedAt = createdat;
            return View(deals);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Deals == null)
            {
                return NotFound();
            }

            var deal = await _context.Deals
                .Include(d => d.Category)
                .Include(d => d.GroupFacebook)
                .Include(d => d.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (deal == null)
            {
                return NotFound();
            }

            return View(deal);
        }

        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.DealCategories, "Id", "Id");
            ViewData["GroupFacebookId"] = new SelectList(_context.GroupFacebooks, "Id", "Id");
            ViewData["UserId"] = new SelectList(_context.AspNetUsers, "Id", "Id");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,ShopeeLink,Code,Slot,ShopeePrice,RefundPrice,IsFreeship,Location,DealExpired,DealExpiredAt,CategoryId,GroupFacebookId,RefundType,Quantity,LinkFacebook,CreatedAt,UpdatedAt,CreatedBy,UpdatedBy,CreatedName,UpdatedName,Status,StatusReason,Note,UserId,ImageDeal,AffiliateLink")] Deal deal)
        {
            if (ModelState.IsValid)
            {
                _context.Add(deal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.DealCategories, "Id", "Id", deal.CategoryId);
            ViewData["GroupFacebookId"] = new SelectList(_context.GroupFacebooks, "Id", "Id", deal.GroupFacebookId);
            ViewData["UserId"] = new SelectList(_context.AspNetUsers, "Id", "Id", deal.UserId);
            return View(deal);
        }

        
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Deals == null)
            {
                return NotFound();
            }
            var deal = await _context.Deals.FindAsync(id);
            if (deal == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.DealCategories, "Id", "Id", deal.CategoryId);
            ViewData["GroupFacebookId"] = new SelectList(_context.GroupFacebooks, "Id", "Id", deal.GroupFacebookId);
            ViewData["UserId"] = new SelectList(_context.AspNetUsers, "Id", "Id", deal.UserId);
            return View(deal);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, string status)
        {

            var deal = await _context.Deals.FindAsync(id);
            if (deal == null)
            {
                return NotFound();
            }

            deal.Status = status;
            deal.StatusReason = 0;
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(deal);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DealExists(deal.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(deal);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Deals == null)
            {
                return NotFound();
            }

            var deal = await _context.Deals
                .Include(d => d.Category)
                .Include(d => d.GroupFacebook)
                .Include(d => d.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (deal == null)
            {
                return NotFound();
            }

            return View(deal);
        }

        // POST: Admin/Deals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Deals == null)
            {
                return Problem("Entity set 'ShopeeAffContext.Deals'  is null.");
            }
            var deal = await _context.Deals.FindAsync(id);
            if (deal != null)
            {
                _context.Deals.Remove(deal);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DealExists(int id)
        {
          return (_context.Deals?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Affiliate_Shopee/Areas/Seller/Controllers/DealsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Affiliate_Shopee.Models;
using static Google.Rpc.Help.Types;
using System.Web.Helpers;
using System.Text.RegularExpressions;
using Google.Protobuf.WellKnownTypes;
using X.PagedList;
using System.Xml.Linq;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.AspNetCore.Authorization;

namespace Affiliate_Shopee.Areas.Seller.Controllers
{
    [Area("Seller")]
    [Authorize(Roles = "Seller")]
    public class DealsController : Controller
    {
        private readonly IWebHostEnvironment _hostingEnvironment;
        private readonly ShopeeAffContext _context;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public DealsController(ShopeeAffContext context, IHttpContextAccessor httpContextAccessor, IWebHostEnvironment hostingEnvironment)
        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;
            _hostingEnvironment = hostingEnvironment;
        }

        // GET: Seller/Deals
        public async Task<IActionResult> Index(int? page, string textsearch, string status, DateTime? createdat)
        {
            UpdateDealStatus();
            var pageNumber = page ?? 1;
            var pageSize = 30;
            var userId = _httpContextAccessor.HttpContext.Request.Cookies["UserId"];
            var query = _context.Deals.Where(d => d.UserId == userId).AsQueryable();

            if (!string.IsNullOrEmpty(textsearch))
            {
                query = query.Where(d => d.Name.Contains(textsearch) || d.Code.Contains(textsearch));
            }
            if (!string.IsNullOrEmpty(status))
            {
                query = query.Where(d => d.Status == status);
            }
            if (createdat.HasValue)
            {
                query = query.Where(d => d.CreatedAt.Value.Date == createdat.Value.Date);
            }
            query = query.OrderByDescending(d => d.CreatedAt);
            var deals = await query.ToPagedListAsync(pageNumber, pageSize);
            ViewBag.TextSearch = textsearch;
            ViewBag.Status = status;
            ViewBag.CreatedAt = createdat;
            return View(deals);
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Deals == null)
            {
                return NotFound();
            }
            var deal = await _context.Deals
                .Include(d => d.Category)
                .Include(d => d.GroupFacebook)
                .Include(d => d.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (deal == null)
            {
                return NotFound();
            }
            return View(deal);
        }
        [HttpPost]
        public IActionResult UpdateStatusReason(int id, int status)
        {
            var item = _context.Deals.FirstOrDefault(i => i.Id == id);
            if (item != null)
            {
                int statusReasonValue = status;
                item.StatusReason = statusReasonValue;
                _context.SaveChanges();
                return Ok();
            }
            else
            {
                return NotFound();
            }
        }
        public void UpdateDealStatus()
        {
            var dealsToExpire = _context.Deals.Where(d => d.DealExpiredAt <= DateTime.Now && d.Status != "Hết hạn" || d.Slot == 0).ToList();
            foreach (var deal in dealsToExpire)
            {
                deal.Status = "Hết hạn";
                deal.StatusReason = 0;
                _context.Update(deal);
            }

            _context.SaveChanges();
        }
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.DealCategories, "Id", "Name");
            ViewData["GroupFacebookId"] = new SelectList(_context.GroupFacebooks, "Id", "Id");
            ViewData["UserId"] = new SelectList(_context.AspNetUsers, "Id", "Id");
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string Nameimg, string Name, string shopeelink, int slot, int shopeeprice,
            int refundprice, int categoryid, string? note, int isfreeship, string location,
            int dealexpired, DateTime? dealexpiredat, IFormFile ImgDeal)
        {
            var uploadsFolder = Path.Combine(_hostingEnvironment.WebRootPath, "image/imagesellerdeals");
            var uniqueFileName = Nameimg;
            var filePath = Path.Combine(uploadsFolder, uniqueFileName);
            var userId = _httpContextAccessor.HttpContext.Request.Cookies["UserId"];
            var checkuserid = await _context.Sellers.FirstOrDefaultAsync(s => s.Userid == userId);
            if (string.IsNullOrEmpty(Nameimg))
            {
                return Json(new { success = false, message = "Vui lòng tải lên hình ảnh." });
            }

            if (string.IsNullOrEmpty(Name))
            {
                return Json(new { success = false, message = "Vui lòng nhập tên sản phẩm." });
            }
            if (dealexpired == 0 && dealexpiredat < DateTime.Now)
            {
                return Json(new { success = false, message = "Thời gian hết hạn phải lớn hơn thời gian hiện tại." });
            }
            if (string.IsNullOrEmpty(shopeelink))
            {
                return Json(new { success = false, message = "Vui lòng nhập liên kết sản phẩm trên Shopee." });
            }

            if (slot < 10)
            {
                return Json(new { success = false, message = "Số lượng slot phải lớn hơn hoặc bằng 10." });
            }

            if (shopeeprice <= 0)
            {
                return Json(new { success = false, message = "Giá trên Shopee phải lớn hơn 0." });
            }

            if (refundprice <= 0)
            {
                return Json(new { success = false, message = "Số tiền hoàn lại phải lớn hơn 0." });
            }
            var name = Regex.Replace(Name.Trim(), @"\s+", " ");
            var existingDealWithName = await _context.Deals.FirstOrDefaultAsync(d => d.Name == name);
            var existingDealWithShopeeLink = await _context.Deals.FirstOrDefaultAsync(d => d.ShopeeLink == shopeelink);
            if (existingDealWithName != null)
            {
                return Json(new { success = false, message = "Tên sản phẩm đã được đặt trước đó." });
            }            
            if (name.Length <= 4 || name.Length >= 100)
            {
                return Json(new { success = false, message = "Tên sản phẩm phải có 4 đến 100 ký tự." });
            }
            if (!shopeelink.Contains("https://shopee.vn/"))
            {
                return Json(new { success = false, message = "Link Shopee không hợp lệ." });
            }
            if (refundprice > shopeeprice)
            {
                return Json(new { success = false, message = "Giá bán phải lớn hơn giá hoàn tiền." });
            }
            if (refundprice < 0.25 * shopeeprice)
            {
                return Json(new { success = false, message = "Giá hoàn tiền phải tối thiểu bằng 25% của giá trên Shopee." });
            }
            if (existingDealWithShopeeLink != null)
            {
                return Json(new { success = false, message = "Link Shopee đã tồn tại trong một deal khác." });
            }

            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                await ImgDeal.CopyToAsync(stream);
            }
            var createdat = DateTime.Now;
            var createdatnow = DateTime.Now;
            var code = "D" + createdat.ToString("ddMMyyHHmmss");
            var status = "Chờ duyệt";
            int dealexpireda = dealexpired;
            var dealexpiredata = dealexpiredat;
            int statusreason = 1;
            if (dealexpiredat == null)
            {
                dealexpired = dealexpireda;
            }
            var deal = new Deal
            {
                UserId = userId,
                ImageDeal = Nameimg,
                Name = name,
                Slot = slot,
                ShopeeLink = shopeelink,
                CreatedAt = createdat,
                Location = location,
                RefundPrice = refundprice,
                ShopeePrice = shopeeprice,
                CategoryId = categoryid,
                IsFreeship = isfreeship,
                Note = note,
                Code = code,
                Status = status,
                StatusReason = statusreason,
                DealExpired = dealexpireda,
                DealExpiredAt = dealexpiredat,
            };
            _context.Deals.Add(deal);
            await _context.SaveChangesAsync();
            TempData["SuccessMessage"] = "Deal đã được tạo thành công!";
            return Json(new { success = true });
        }
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null || _context.Deals == null)
            {
                return NotFound();
            }

            var deal = await _context.Deals.FindAsync(id);
            if (deal == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.DealCategories, "Id", "Name", deal.CategoryId);
            ViewData["GroupFacebookId"] = new SelectList(_context.GroupFacebooks, "Id", "Id", deal.GroupFacebookId);
            ViewData["UserId"] = new SelectList(_context.AspNetUsers, "Id", "Id", deal.UserId);
            return View(deal);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

Affiliate_Shopee/Areas/Admin/Views/Deals/Edit.cshtml
@model Affiliate_Shopee.Models.Deal
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout_admin.cshtml";
}


<link rel="stylesheet" href="~/css/deal_create.css" />
<h5 style="font-size:20px;margin-left:10px;color:#333;font-weight:700">Thông tin deal</h5>
@* <h5 style="font-size:15px;margin-left:10px;color:#333">Kênh người bán > Sửa thông tin deal</h5> *@
<hr />
<div>
    <div class="row" style="margin:20px;justify-content:center">
        <div class="col-md-4">
            <form asp-action="Edit" method="post">
                <div class="form-group">
                    <label asp-for="Status" class="control-label">Trạng thái hiện tại: @Html.DisplayFor(model => model.Status)</label>
                    <select asp-for="Status" class="form-control">
                        <option value="Đang hoạt động">Duyệt deal</option>
                        <option value="Khóa deal">Khóa deal</option>
                        <option value="Đang hoạt động">Bỏ khóa</option>
                    </select>
                </div>
                <input type="hidden" asp-for="Status" />
                <input type="submit" class="btn btn-primary" value="Lưu" />
            </form>
            <div class="form-group">
                <label asp-for="ImageDeal" class="control-label">Hình ảnh: <span style="color:red">*</span></label>
                <div style="display:flex">
                    @if (!string.IsNullOrEmpty(Model.ImageDeal))
                    {
                        <img src="~/image/imagesellerdeals/@Model.ImageDeal" style="width:100px;height:100px;margin-left:5px" />
                    }
                    else
                    {
                        <span>Không có ảnh</span>
                    }
                </div>
                <span id="ImageDealError" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">Tên sản phẩm: </label><br />
                @Html.DisplayFor(model => model.Name)
            </div>
            <div class="form-group">
                <label asp-for="ShopeeLink" class="control-label">Link sản phẩm trên Shoppe:</label> <br />
                <a href="@Model.ShopeeLink" target="_blank">@Model.ShopeeLink</a>
            </div>
            <div class="form-group">
                <label asp-for="Slot" class="control-label">Số lượng Slot:</label>
                @Html.DisplayFor(model => model.Slot)
            </div>

            <div class="form-group">
                <label asp-for="Note" class="control-label">Ghi chú: </label>
                @Html.DisplayFor(model => model.Note)
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="ShopeePrice" class="control-label">Giá trên sàn: </label>
                @Html.DisplayFor(model => model.ShopeePrice) vnđ
            </div>
            <div class="form-group">
                <label asp-for="RefundPrice" class="control-label">Số tiền hoàn lại:  </label>
                @Html.DisplayFor(model => model.RefundPrice) vnđ
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label">Danh mục Deal: </label>
                @Html.DisplayFor(model => model.Category.Name)
            </div>
            <div class="form-group">
                <label asp-for="IsFreeship" class="control-label">Free Ship Extra: </label>
                @Html.DisplayFor(model => model.IsFreeship)
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label">Khu vực của shop: </label>
                @Html.DisplayFor(model => model.Location)
            </div>

            <div class="form-group">
                <label class="control-label">Loại hết hạn của Deal:<span style="color:red">*</span> </label> <br />
                @Html.DisplayFor(model => model.DealExpiredAt)
            </div>
        </div>
        <input type="hidden" id="Nameimg" name="Nameimg" />
    </div>
</div>

Affiliate_Shopee/Areas/Admin/Views/Deals/Index.cshtml
@model X.PagedList.IPagedList<Affiliate_Shopee.Models.Deal>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout_admin.cshtml";
    var i = 1;
}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="~/css/sellerDealIndex.css" />
<div class="container-fluid">
    <div class="row mt-3 mb-4">
        <div class="col-md-6">
            <h4>Quản lý Deal</h4>
            <div id="toast-container" class="toast-top-right"></div>
        </div>
    </div>
    <div style="background-color:#f5f5f5;margin:5px;padding:10px">
        <div class="row" style="justify-content:center;">
            <div class="col-md-2" style="padding-right:0px">
                <div class="input-group mb-3">
                    <input type="text" class="form-control" id="textsearch" placeholder="Tìm kiếm theo mã Deal" data-page-number="@Model.PageNumber">
                </div>
            </div>
            <div class="col-md-2" style="padding-right:0px">
                <div class="input-group mb-3">
                    <select id="statusDropdown" class="form-select" style="width:100%;" data-page-number="@Model.PageNumber">
                        <option value="">Chọn trạng thái</option>
                        <option value="Chờ duyệt">Chờ duyệt</option>
                        <option value="Đang hoạt động">Đang hoạt động</option>
                        <option value="Khóa deal">Đã khóa</option>
                        <option value="Hết hạn">Hết hạn</option>
                        <option value="All">Tất cả</option>
                    </select>
                </div>
            </div>
            <div class="col-md-2" style="padding-right:0px">

                <div class="input-group">
                    <input type="date" class="form-control" id="createdAtInput">
                </div>
            </div>
            <div class="col-md-2">
                <div class="input-group">
                    <button id="filterButton" class="btn btn-primary" style="margin-right:5px;"><i class="fa-solid fa-magnifying-glass"></i></button>
                    <button id="cancelButton" class="btn btn-danger"><i class="fa-solid fa-rotate-right"> </i></button>
                </div>
            </div>
        </div>
        <div class="container" style="margin-left:500px">
           
        </div>
        <div class="card shadow">
            <div class="card-body">
                <div class="row justify-content-center">
                    <div class="col-auto">
                        <nav aria-label="Page navigation">
                            <ul class="pagination justify-content-center">
                                @if (Model.HasPreviousPage)
                                {
                                    <li class="page-item">
                                        <a class="page-link" href="@Url.Action("Index", new { page = Model.PageNumber - 1,textsearch = ViewBag.TextSearch, status = ViewBag.Status, createdat = ViewBag.CreatedAt,  })" aria-label="Previous">
                                            <span aria-hidden="true">&laquo;</span>
                                        </a>
                                    </li>
                                }
                                @for (var pageNumber = 1; pageNumber <= Model.PageCount; pageNumber++)
                                {
                                    <li class="page-item @(pageNumber == Model.PageNumber ? "active" : "")">
                                        <a class="page-link" href="@Url.Action("Index", new { page = pageNumber,textsearch = ViewBag.TextSearch, status = ViewBag.Status, createdat = ViewBag.CreatedAt })">@pageNumber</a>
                                    </li>
                                }
                                @if (Model.HasNextPage)
                                {
                                    <li class="page-item">
                                        <a class="page-link" href="@Url.Action("Index", new { page = Model.PageNumber + 1,textsearch = ViewBag.TextSearch, status = ViewBag.Status, createdat = ViewBag.CreatedAt })" aria-label="Next">
                                            <span aria-hidden="true">&raquo;</span>
                                        </a>
                                    </li>
                                }
                            </ul>
                        </nav>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0" style="text-align:center">
                        <thead>
                            <tr>
                                <th>STT</th>
                                <th>Mã Deal</th>
                                <th>Tên Deal</th>
                                <th>Ngày tạo</th>
                                <th>Tên người bán</th>
                                <th>Trạng thái</th>

                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.Any())
                            {
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@(((Model.PageNumber - 1) * Model.PageSize) + (i))</td>
                                        <td>@(item.Code)</td>
                                        <td style="text-align:left"> <a asp-action="Details" asp-controller="Deals" asp-route-id="@item.Id" style="text-decoration:none">@Html.DisplayFor(modelItem => item.Name)</a></td>
                                        <td>@string.Format("{0:dd/MM/yyyy HH:mm:ss}", item.CreatedAt)</td>
                                        <td>
                                            @if (item.User != null)
                                            {
                                                @item.User.Name
                                            }
                                            else
                                            {
                                                <text>N/A</text>
                                            }
                                        </td>
                                        <td>
                                            <div style="border-radius:10px;width:150px;margin:0 auto;color:white;background-color:
                                         @if (item.Status == "Chờ duyệt")
                                         {
                                            <text>#3897E9</text>
                                        }
                                        else if (item.Status == "Đang hoạt động")
                                        {
                                            <text>#2A2A86</text>
                                        }
                                        else if (item.Status == "Khóa deal")
                                        {
                                            <text>
                                                #660000
                                            </text>
                                        }
                                        else if (item.Status == "Hết hạn")
                                        {
                                            <text>#171A1F</text>
                                        }
                                        ;">@item.Status</div>
                                        </td>


                                    </tr>
                                    i++;
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="7" style="text-align: center;">Không có dữ liệu.</td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-auto">
                        <nav aria-label="Page navigation">
                            <ul class="pagination">
                                @if (Model.HasPreviousPage)
                                {
                                    <li class="page-item">
                                        <a class="page-link" href="@Url.Action("Index", new { page = Model.PageNumber - 1,textsearch = ViewBag.TextSearch, status = ViewBag.Status, createdat = ViewBag.CreatedAt,  })" aria-label="Previous">
                                            <span aria-hidden="true">&laquo;</span>
                                        </a>
                                    </li>
                                }
                                @for (var pageNumber = 1; pageNumber <= Model.PageCount; pageNumber++)
                                {
                                    <li class="page-item @(pageNumber == Model.PageNumber ? "active" : "")">
                                        <a class="page-link" href="@Url.Action("Index", new { page = pageNumber,textsearch = ViewBag.TextSearch, status = ViewBag.Status, createdat = ViewBag.CreatedAt })">@pageNumber</a>
                                    </li>
                                }
                                @if (Model.HasNextPage)
                                {
                                    <li class="page-item">
                                        <a class="page-link" href="@Url.Action("Index", new { page = Model.PageNumber + 1,textsearch = ViewBag.TextSearch, status = ViewBag.Status, createdat = ViewBag.CreatedAt })" aria-label="Next">
                                            <span aria-hidden="true">&raquo;</span>
                                        </a>
                                    </li>
                                }
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts
    {
    <script src="~/js/AdminDealIndexjs.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
}