Affiliate_Shopee/Models/DealCategory.cs
using System;
using System.Collections.Generic;

namespace Affiliate_Shopee.Models
{
    public partial class DealCategory
    {
        public DealCategory()
        {
            Deals = new HashSet<Deal>();
        }

        public int Id { get; set; }
        public string? Name { get; set; }
        public int? Status { get; set; }
        public string? Image { get; set; }

        public virtual ICollection<Deal> Deals { get; set; }
    }
}

Affiliate_Shopee/Controllers/DealCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Affiliate_Shopee.Models;
using X.PagedList;

namespace Affiliate_Shopee.Controllers
{
    public class DealCategoriesController : Controller
    {
        private readonly ShopeeAffContext _context;

        public DealCategoriesController(ShopeeAffContext context)
        {
            _context = context;
        }

        // GET: DealCategories
        public async Task<IActionResult> Index()
        {
              return _context.DealCategories != null ? 
                          View(await _context.DealCategories.ToListAsync()) :
                          Problem("Entity set 'ShopeeAffContext.DealCategories'  is null.");
        }

        // GET: DealCategories/Details/5
        public async Task<IActionResult> Details(int? id, int? page)
        {
            if (id == null)
            {
                return NotFound();
            }
            ViewBag.Id = id;
            var dealCategory = await _context.DealCategories.FirstOrDefaultAsync(m => m.Id == id);
            if (dealCategory == null)
            {
                return NotFound();
            }

            var pageNumber = page ?? 1; // Trang hiện tại, nếu không có trang nào được chọn thì mặc định là trang 1
            var pageSize = 18; // Số mục trên mỗi trang

            var deals = await _context.Deals.Where(d => d.CategoryId == id && d.Status == "Đang hoạt động" && d.StatusReason == 1).ToPagedListAsync(pageNumber, pageSize);
            ViewBag.DealCategoryName = dealCategory.Name;

            return View(deals);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Status")] DealCategory dealCategory)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dealCategory);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(dealCategory);
        }

        // GET: DealCategories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.DealCategories == null)
            {
                return NotFound();
            }

            var dealCategory = await _context.DealCategories.FindAsync(id);
            if (dealCategory == null)
            {
                return NotFound();
            }
            return View(dealCategory);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Status")] DealCategory dealCategory)
        {
            if (id != dealCategory.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dealCategory);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DealCategoryExists(dealCategory.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dealCategory);
        }

        // GET: DealCategories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.DealCategories == null)
            {
                return NotFound();
            }

            var dealCategory = await _context.DealCategories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (dealCategory == null)
            {
                return NotFound();
            }

            return View(dealCategory);
        }

        // POST: DealCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.DealCategories == null)
            {
                return Problem("Entity set 'ShopeeAffContext.DealCategories'  is null.");
            }
            var dealCategory = await _context.DealCategories.FindAsync(id);
            if (dealCategory != null)
            {
                _context.DealCategories.Remove(dealCategory);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DealCategoryExists(int id)
        {
          return (_context.DealCategories?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Affiliate_Shopee/Views/DealCategories/Create.cshtml
@model Affiliate_Shopee.Models.DealCategory

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>DealCategory</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Affiliate_Shopee/Views/DealCategories/Delete.cshtml
@model Affiliate_Shopee.Models.DealCategory

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DealCategory</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Affiliate_Shopee/Views/DealCategories/Details.cshtml
@model X.PagedList.IPagedList<Affiliate_Shopee.Models.Deal>
@using X.PagedList.Mvc.Core;
@using X.PagedList;
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
    ShopeeAffContext db = new ShopeeAffContext();
    var dealcategories = db.DealCategories.ToPagedList(); // Phân trang cho dealcategories
}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link rel="stylesheet" href="~/css/homeIndex.css" />
<link rel="stylesheet" href="~/css/slideCategory.css" />
<script src="../bizweb.dktcdn.net/100/270/860/themes/606449/assets/appear24cb.js?1705895589400" type="text/javascript"></script>

<section class="awe-section-3">
    <div class="container dg-fix">
        <div class="section_group_product section_group_product_1 search-group-new">
            <div class="header_search">
                <div class="input-group">
                    <fieldset class="form-group">
                        <div class="col-lg-12 col-md-12">
                            <div class="clearfix" id="dealCategoriesContainer">
                                @foreach (var item in dealcategories)
                                {
                                    <div class="col-md-2 col-sm-6 col-xs-12 deal-item" style="text-align: center;">
                                        <a href="@Url.Action("Details", "DealCategories", new { id = item.Id })">
                                            <img style="width: 70px;" src="~/image/@item.Image" alt="">
                                        </a>
                                        <h6><a href="@Url.Action("Details", "DealCategories", new { id = item.Id })">@Html.DisplayFor(modelItem => item.Name)</a></h6>
                                    </div>
                                }
                                @for (int i = dealcategories.Count(); i < 6; i++)
                                {
                                    <div class="col-md-2 col-sm-6 col-xs-12 deal-item" style="text-align: center;">
                                        <a href="#">
                                            <img style="width: 70px;" src="~/image/ddđ.png" alt="">
                                        </a>
                                        <h6><a href="#"></a></h6>
                                    </div>
                                }
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
            <div class="dg-pagination">
                <button class="btn dg-fixbutton" id="prevSlide" disabled><i class="fa-solid fa-chevron-left"></i></button>
                <button class="btn dg-fixbutton" id="nextSlide"><i class="fa-solid fa-chevron-right"></i></button>
            </div>
        </div>
    </div>
</section>


<section class="awe-section-4">
    <div class="container">
        <div class="section_group_product section_group_product_1">
            <div class="barbox clearfix">
                <h2 class="titlecate">@ViewBag.DealCategoryName</h2>
            </div>
            <div class="clearfix"></div>
            <div class="row list-product">
                @foreach (var item in Model)
                {
                    <div class="col-md-2 col-sm-4 col-xs-6 evo-item-product">
                        <div class="product-box">
                            <div class="product-thumbnail">
                                <div class="sale-flash">SALE</div>
                                <a href="@Url.Action("Details", "Deals", new { id = item.Id })"
                                   title="@Html.DisplayFor(modelItem => item.Name)">
                                    <img src="/image/imagesellerdeals/@item.ImageDeal"
                                         alt="@item.Name"
                                         class="img-responsive center-block" />
                                </a>
                            </div>
                            <div class="product-info a-center">
                                <a class="product-name" href="@Url.Action("Details", "Deals", new { id = item.Id })"
                                   title="@Html.DisplayFor(modelItem => item.Name)">
                                    @Html.DisplayFor(modelItem => item.Name)
                                </a>
                                <div class="price-box clearfix">
                                    <div class="product-price" style="font-size:15px;color:#379AE6">Giá: @string.Format("{0:0,0}", item.ShopeePrice) đ</div>
                                    <div class="special-price product-price">Hoàn tiền: @string.Format("{0:0,0}", item.RefundPrice)đ</div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="container">
                <div class="text-center">
                    <nav aria-label="Page navigation">
                        <ul class="pagination">
                            @if (Model.HasPreviousPage)
                            {
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action("Details", new { page = Model.PageNumber - 1, id = ViewBag.Id })" aria-label="Previous">
                                        <span aria-hidden="true">&laquo;</span>
                                        <span class="sr-only">Previous</span>
                                    </a>
                                </li>
                            }

                            @for (var i = 1; i <= Model.PageCount; i++)
                            {
                                <li class="page-item @(i == Model.PageNumber ? "active" : "")">
                                    <a class="page-link" href="@Url.Action("Details", new { page = i, id = ViewBag.Id })">@i</a>
                                </li>
                            }

                            @if (Model.HasNextPage)
                            {
                                <li class="page-item">
                                    <a class="page-link" href="@Url.Action("Details", new { page = Model.PageNumber + 1, id = ViewBag.Id })" aria-label="Next">
                                        <span aria-hidden="true">&raquo;</span>
                                        <span class="sr-only">Next</span>
                                    </a>
                                </li>
                            }
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</section>

@section Scripts
    {
    <script src="~/js/slideCategories.js"></script>
}

Affiliate_Shopee/Views/DealCategories/Edit.cshtml
@model Affiliate_Shopee.Models.DealCategory

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>DealCategory</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Affiliate_Shopee/Views/DealCategories/Index.cshtml
@model IEnumerable<Affiliate_Shopee.Models.DealCategory>


@{
    ViewData["Title"] = "Index";
    ShopeeAffContext db = new ShopeeAffContext();
    var dealcategories = db.DealCategories.ToList();
}
<section class="awe-section-3">
    <div class="container">
        <div class="section_group_product section_group_product_1 search-group-new">
            <div class="header_search">
                <div class="input-group ">
                    <fieldset class="form-group">
                        <div class="col-lg-12 col-md-12">
                            <div class="clearfix">
                                @foreach (var item in dealcategories)
                                {
                                    <div class="col-md-2 col-sm-6 col-xs-12" style="text-align: center;">
                                        <a href="@Url.Action("Details", "DealCategories",new { id = item.Id })">
                                            <img style="width: 70px;" src="https://img.tgdd.vn/imgt/f_webp,fit_outside,quality_100/https://cdn.tgdd.vn//content/Laptop-129x129.png" alt="">
                                        </a>
                                        <h6><a href="@Url.Action("Details", "DealCategories",new { id = item.Id })">@Html.DisplayFor(modelItem => item.Name)</a></h6>
                                    </div>
                                }
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
        </div>
    </div>
</section>